### PR TITLE
edited binding return value

### PR DESCRIPTION
**Pull request by msaikaushik**

### CODE REVIEW

**Review by eavichay — CHANGES_REQUESTED** [review]
Hey. It could be simpler than that. I hope you don't mind helping you out a bit.
The matcher function should be `(attr) => attr.nodeName.indexOf('bind:') === 0`

The execution function should only be changed to `const tAttr = attribute.nodeName.substring(6)`

It could be less code.

WDYT?

Please do not open a new PR, just force push on this one.

10x.

**Comment by msaikaushik** [comment]
@eavichay ,correct me if i'm wrong, should'nt the substring start from index 5? or do you expect a white space after `bind:`

and should i return the whole attr.nodeName in the if's execution part?

thank you.

**Comment by eavichay** [comment]
right, my bad.

**Comment by msaikaushik** [comment]
now?

**Comment by msaikaushik** [comment]
@eavichay , Do i need to change anything on the latest commit?

**Review by eavichay — APPROVED** [review]

**Comment by msaikaushik** [comment]
thank you very much, @eavichay !

**Pull request merged**
