### PR TITLE
Update ts declare file, to be valid

### PR DESCRIPTION
**Pull request by SheepFromHeaven**

### CODE REVIEW

**Comment by eavichay** [comment]
Thanks. Looks good. Question: why did the static getters were changed to regular methods?

**Comment by SheepFromHeaven** [comment]
Static getters and setters are not allowed in declaration files. https://stackoverflow.com/q/39534455/8383975

**Comment by eavichay** [comment]
Ok.
FYI:
rxInject, rxProp, rxMethod - readonly,
executePlugins, wrapGetterSetter - should be private
template - protected readonly (????) I'm not a typescript expert.
useShadow - boolean that is set once on init (protected readonly)?

I'm not sure which other should be also private. In the world of Javascript there is no private, and I haven't thought of what should be public or not if your'e in a Typescript approach :)

WDYT?

**Comment by SheepFromHeaven** [comment]
@eavichay readonly is not a valid option in a declaration file. By having a function with no parameters it is readonly.

Made privates private.

And fixed a typo ;)

**Pull request merged**
